### ISSUE TITLE
Missing functionality of registering custom functions

### ISSUE THREAD

**Issue by josefalanga** [relaypro-open/YarnRunner-Python#5]
[Defining Functions - Documentation](https://docs.yarnspinner.dev/using-yarnspinner-with-unity/creating-commands-functions#defining-functions)

I tried the sample yarn code from the docs above, `One plus one is {add_numbers(1, 1)}` setting a handler with `runner.add_command_handler("add_numbers", fn)`. The result is an exception: `Exception: The internal function 'add_numbers' is not implemented in this Yarn runtime.`

I took a look, and when executing functions, the runner only tries to match them with `std_lib_functions`.

Looks like a good opportunity to implement `runner.add_function_handler` or use the existing `runner.add_command_handler` to register custom functions, and then look up for them in `__call_func` before throwing the exception. This would allow to implement `dice`, and other [built-in functions](https://docs.yarnspinner.dev/getting-started/writing-in-yarn/functions#built-in-functions), as well as custom functions like the sample from the docs.

This functions are specially usefull because they can be used inside expressions, like this:
```
// Inside an if statement:
<<if dice(6) == 6>>
    You rolled a six!
<<endif>>

// Inside a line:
Gambler: My lucky number is {random_range(1,10)}!
```
I was about to jump to code this, but something catched my attention from the README:

> The known features currently missing are:
> An appropriate replacement for the distinction Yarn makes between Functions and Coroutines in Unity (to allow users to register blocking command handlers via this Python runner independent of Unity)

Should I take this Coroutines stuff in consideration while adding function handlers? Looks related to the missing `<<wait>>`  built-in command too.

Maybe it's better to split the task, make custom functions possible in the fist place, and in another Issue/PR treat the Coroutines/blocking/wait stuff.

**Comment by weaversam8** [comment]
Hey Jose, thanks for opening an issue - this is definitely something that's helpful to talk about before adding.

My thoughts:

- a "Coroutine" is a [Unity term](https://docs.unity3d.com/Manual/Coroutines.html) referring to a specific type of function that is designed for performing execution across multiple frames. YarnSpinner-Unity uses these to allow a function to "block" execution of dialogue until the coroutine returns. Since our runner is already single-threaded (based on how Python works), any call to a command should block already.
  - since commands already block, perhaps it would be better to change the above README to:
    > (to allow users to register ~~blocking~~ **asynchronous** command handlers via this Python runner independent of Unity)
- I don't think we should reuse `add_command_handler`, I do think it's better to add a new function `add_function_handler`, though I think having two APIs with such similar names could be confusing. We should add a note to the README or tests in #6 to clarify.

**Comment by josefalanga** [comment]
Well, you have a point there, for it to faithfully replicate Unity's coroutines, it should be asynchronous, so the main thread is not blocked while waiting for the runner. That async behaviour would be specially usefull for cases like using the runner server side, but requires converting the whole runner into async. AFAIK, that's a lot of effort for for a very small benefit, and totally not whorty of facing it right now.

I'll limit the PR to only custom function handlers then. On that subject, I totally agree with you, I'll implement the suggestions right away.
